### ISSUE TITLE
what is causing this issue?

### ISSUE THREAD

**Issue by Vinni-Cedraz** [conda-forge/bear-feedstock#24]
### Comment:

I'm installing exactly as the readme instructs:
`conda config --add channels conda-forge
conda config --set channel_priority strict
conda install bear`

but still I'm getting a symbol lookup error: 
`bear: symbol lookup error: bear: undefined symbol: _ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt2v817basic_string_viewIcEENS_5level10level_enumES6_`

**Comment by h-vetinari** [comment]
This might be related to https://github.com/conda-forge/bear-feedstock/pull/24 - those builds were marked broken.

Could you try again please, and post the output of `conda list` & `conda info`?

**Comment by h-vetinari** [comment]
Closing as stale, please create a new issue if problems persist.
